<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<div class="block block-dashboard-addresses">
    <div class="block-title">
        <h2>Account Overview</h2>
    </div>
    <div class="personal-information">
        <h4>Personal Information</h4>
        <table>
            <tr>
                <td>Name:</td>
                <td>Firstname Lastname</td>
            </tr>
            <tr>
                <td>Email:</td>
                <td>email@domain.com</td>
            </tr>
            <tr>
                <td>Phone No:</td>
                <td>0932121122</td>
            </tr>
        </table>
    </div>
    <div class="default-address">
        <h4>Default Address</h4>
        <table>
            <tr>
                <td><b>Default Shipping Address</b></td>
                <td><b>Default Shipping Address</b></td>
            </tr>
            <td>
                <p>Address Name<br></p>
                
                

            </td>
            <td>
                <p>Address Name</p>
                <p>Firstname Lastname</p>
            </td>
        </table>
    </div>
</div>
