<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="block block-dashboard-info">
    <div class="block-title">
        <b>Hi, Firstname</b>
        <p>From your account dashboard, you have ability to view a snapshot of</br>your recent acivities and easily update your information</p>
    </div>
</div>
