<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Edit $block */
?>

<form class="form form-edit-account" action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Personal Information')) ?></span></legend><br>
       
        <div class="field field-name-firstname required">
            <label class="label" for="firstname"><span>First Name</span></label>
            <div class="control">
                <input type="text" id="firstname" name="firstname" value="thu" title="First Name" class="input-text required-entry" data-validate="{required:true}" aria-required="true">
            </div>
        </div>
        <div class="field field-name-firstname required">
            <label class="label" for="firstname"><span>Last Name</span></label>
            <div class="control">
                <input type="text" id="firstname" name="firstname" value="thu" title="First Name" class="input-text required-entry" data-validate="{required:true}" aria-required="true">
            </div>
        </div>
        <div class="field field-name-firstname required">
            <label class="label" for="firstname"><span>Email</span></label>
            <div class="control">
                <input type="text" id="firstname" name="firstname" value="thu" title="First Name" class="input-text required-entry" data-validate="{required:true}" aria-required="true">
            </div>
        </div>
        <div class="field field-name-firstname required">
            <label class="label" for="firstname"><span>Date of Birth</span></label>
            <div class="control">
                <input type="text" id="firstname" name="firstname" value="thu" title="First Name" class="input-text required-entry" data-validate="{required:true}" aria-required="true">
            </div>
        </div>
    </fieldset>

    
    <?= $block->getChildHtml('form_additional_info') ?>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Update')) ?>"><span><?= $block->escapeHtml(__('Update')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>